# Generated by Django 5.2.17 on 2026-09-08 14:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('staff_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(choices=[('therapist', 'Therapist'), ('receptionist', 'Receptionist'), ('accountant', 'Accountant'), ('support_staff', 'Support Staff'), ('cleaner', 'Cleaner'), ('other', 'Other')], max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('joined_at', models.DateField()),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='branches.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(max_length=255)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_bonuses_awarded', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_bonuses', to='branches.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='staff.staffmember')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('on_leave', 'On Leave'), ('absent', 'Absent')], max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_attendance_records', to='branches.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.staffmember')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['branch', 'name'], name='staff_staff_branch__6f7e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['branch', 'status'], name='staff_staff_branch__1b192e_idx'),
        ),
        migrations.AddIndex(
            model_name='staffbonus',
            index=models.Index(fields=['staff', '-created_at'], name='staff_staff_staff_i_05bbc1_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['branch', 'date'], name='staff_staff_branch__64e4df_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['staff', '-date'], name='staff_staff_staff_i_b00a91_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.UniqueConstraint(fields=('staff', 'date'), name='uniq_staff_attendance_per_day'),
        ),
    ]
