# Generated by Django 5.2.17 on 2026-09-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_salarypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('early_leave', 'Early Leave'), ('on_leave', 'On Leave'), ('absent', 'Absent')], max_length=16),
        ),
    ]
