# Generated by Django 5.2.17 on 2026-09-09 07:58

from django.db import migrations, models


def convert_late_to_present(apps, schema_editor):
    """"Late" is being retired as a status — arrival time no longer changes the outcome, so fold any existing rows into Present rather than leaving them on a choice the app no longer understands."""
    StaffAttendance = apps.get_model("staff", "StaffAttendance")
    StaffAttendance.objects.filter(status="late").update(status="present")


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffattendance_status'),
    ]

    operations = [
        migrations.RunPython(convert_late_to_present, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('early_leave', 'Early Leave'), ('on_leave', 'On Leave'), ('absent', 'Absent')], max_length=16),
        ),
    ]
