# Generated by Django 5.2.17 on 2026-09-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_late_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
    ]
