# Generated by Django 5.2.17 on 2026-08-30 03:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('upcoming', 'Upcoming'), ('overdue', 'Overdue'), ('written_off', 'Written off')], db_index=True, default='upcoming', max_length=16)),
                ('due_date', models.DateField(db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('index', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated')], db_index=True, default='active', max_length=16)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('upcoming', 'Upcoming'), ('overdue', 'Overdue'), ('written_off', 'Written off')], db_index=True, default='upcoming', max_length=16)),
                ('due_date', models.DateField(db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('label', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated')], db_index=True, default='active', max_length=16)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_code', models.CharField(db_index=True, max_length=48, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('time', models.CharField(max_length=16)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='confirmed', max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='branches.branch')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
