# Generated by Django 5.2.17 on 2026-08-30 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('patients', '0001_initial'),
        ('payments', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service'),
        ),
        migrations.AddField(
            model_name='installment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='services.service'),
        ),
        migrations.AddField(
            model_name='installment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='enrollments.installmentplan'),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='monthlyenrollment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_enrollments', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='monthlyenrollment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_enrollments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='monthlyenrollment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_enrollments', to='services.service'),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='enrollments.monthlyenrollment'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['branch', 'date'], name='enrollments_branch__12374c_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['branch', 'status'], name='enrollments_branch__1c2566_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['patient', 'status'], name='enrollments_patient_6edb29_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['service', 'status'], name='enrollments_service_5c83d0_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['status', 'due_date'], name='enrollments_status_ee0f1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('plan', 'index'), name='uniq_installment_per_plan_index'),
        ),
        migrations.AddIndex(
            model_name='monthlyenrollment',
            index=models.Index(fields=['branch', 'status'], name='enrollments_branch__dd81db_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyenrollment',
            index=models.Index(fields=['patient', 'status'], name='enrollments_patient_5dbaa1_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyenrollment',
            index=models.Index(fields=['service', 'status'], name='enrollments_service_f4e4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlybill',
            index=models.Index(fields=['status', 'due_date'], name='enrollments_status_37aa01_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlybill',
            constraint=models.UniqueConstraint(fields=('enrollment', 'month'), name='uniq_bill_per_enrollment_month'),
        ),
    ]
