# Generated by Django 5.2.17 on 2026-09-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='starts_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
