# Generated by Django 5.2.17 on 2026-09-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('enrollments', '0003_installmentplan_ends_on_installmentplan_starts_on'),
        ('patients', '0002_patient_client_created_at_patient_idempotency_key'),
        ('services', '0005_service_branch_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyenrollment',
            name='terminated_kind',
            field=models.CharField(blank=True, choices=[('manual', 'Stopped by a manager'), ('unpaid_due', "Stopped automatically — the month's due went unpaid")], db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='monthlyenrollment',
            name='terminated_month',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddIndex(
            model_name='monthlyenrollment',
            index=models.Index(fields=['branch', 'terminated_kind', '-terminated_at'], name='enrollments_branch__3d0ea5_idx'),
        ),
    ]
