# Generated by Django 5.2.17 on 2026-09-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_alter_installment_status_alter_monthlybill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('upcoming', 'Upcoming'), ('overdue', 'Overdue'), ('written_off', 'Written off'), ('cancelled', 'Cancelled'), ('advance', 'Paid in advance')], db_index=True, default='upcoming', max_length=16),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('upcoming', 'Upcoming'), ('overdue', 'Overdue'), ('written_off', 'Written off'), ('cancelled', 'Cancelled'), ('advance', 'Paid in advance')], db_index=True, default='upcoming', max_length=16),
        ),
    ]
