# Generated by Django 5.2.17 on 2026-09-28 15:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_alter_installment_status_alter_monthlybill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='discount_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='kind',
            field=models.CharField(choices=[('admission', 'Admission'), ('monthly', 'Monthly fee')], default='monthly', max_length=16),
        ),
        migrations.AddField(
            model_name='monthlyenrollment',
            name='client_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyenrollment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
