# Generated by Django 5.2.17 on 2026-08-30 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsaleitem',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='payments.payment'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['branch', 'name'], name='materials_m_branch__d04ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['branch', 'quantity'], name='materials_m_branch__adac31_idx'),
        ),
        migrations.AddIndex(
            model_name='materialmovement',
            index=models.Index(fields=['material', '-created_at'], name='materials_m_materia_572f60_idx'),
        ),
        migrations.AddIndex(
            model_name='materialsaleitem',
            index=models.Index(fields=['payment'], name='materials_m_payment_98f4e2_idx'),
        ),
    ]
