# Generated by Django 5.2.17 on 2026-08-30 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('system_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('over', 'Over'), ('short', 'Short')], db_index=True, max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closings', to='branches.branch')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyClosingAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_actual_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('corrected_actual_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('amended_at', models.DateTimeField(auto_now_add=True)),
                ('amended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_amendments', to=settings.AUTH_USER_MODEL)),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='dailyclosing.dailyclosing')),
            ],
            options={
                'ordering': ['amended_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyclosing',
            index=models.Index(fields=['branch', '-date'], name='dailyclosin_branch__503fa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyclosing',
            constraint=models.UniqueConstraint(fields=('branch', 'date'), name='uniq_closing_per_branch_day'),
        ),
    ]
