# Generated by Django 5.2.17 on 2026-08-30 03:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('category', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('installment', 'Installment'), ('online', 'Online')], db_index=True, max_length=16)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('original_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_online', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('duration_label', models.CharField(blank=True, max_length=100)),
                ('sessions_label', models.CharField(blank=True, max_length=100)),
                ('expiry_label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='services_se_categor_d8f4e5_idx')],
            },
        ),
    ]
