# Generated by Django 5.2.17 on 2026-09-01 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='review_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=16),
        ),
        migrations.AddField(
            model_name='service',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['review_status'], name='services_se_review__cd4557_idx'),
        ),
    ]
