# Generated by Django 5.2.17 on 2026-09-28 15:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_packageactionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='admission_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
