# Generated by Django 5.2.17 on 2026-08-30 03:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('materials', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(db_index=True, max_length=48, unique=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=48, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer'), ('online_payment', 'Online Payment'), ('card', 'Card')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('upcoming', 'Upcoming'), ('partial', 'Partially refunded'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('void', 'Void')], db_index=True, default='paid', max_length=16)),
                ('category', models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('installment', 'Installment'), ('online', 'Online'), ('material_sale', 'Material sale')], db_index=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('client_created_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='branches.branch')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('bill_action', models.CharField(choices=[('reopen', 'Reopen the bill'), ('write_off', 'Write off the bill')], default='reopen', max_length=16)),
                ('refund_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer'), ('online_payment', 'Online Payment'), ('card', 'Card')], max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='branches.branch')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='payments.payment')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='materials.material')),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.refundrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['branch', '-created_at'], name='payments_pa_branch__2b46ed_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['branch', 'status', '-created_at'], name='payments_pa_branch__a4861c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient', '-created_at'], name='payments_pa_patient_adcd65_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['category'], name='payments_pa_categor_7151bb_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status', '-requested_at'], name='payments_re_status_fd703c_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['branch', 'status'], name='payments_re_branch__d5fe6a_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequestitem',
            index=models.Index(fields=['refund_request'], name='payments_re_refund__b7c329_idx'),
        ),
    ]
