# Generated by Django 5.2.17 on 2026-08-30 03:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('last_value', models.BigIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'year'], name='common_code_scope_cc1439_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'year'), name='uniq_sequence_scope_year')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('soft_delete', 'Soft delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('void', 'Void'), ('refund_request', 'Refund requested'), ('refund_approve', 'Refund approved'), ('refund_reject', 'Refund rejected'), ('terminate', 'Terminate'), ('amend', 'Amend'), ('write_off', 'Write off'), ('login', 'Login')], db_index=True, max_length=32)),
                ('target_type', models.CharField(db_index=True, max_length=64)),
                ('target_id', models.CharField(db_index=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='branches.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='common_audi_target__65ba7e_idx'), models.Index(fields=['-created_at'], name='common_audi_created_fa4caf_idx')],
            },
        ),
    ]
