# Generated by Django 5.2.17 on 2026-09-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.BigIntegerField(unique=True)),
                ('version', models.BigIntegerField(default=0)),
            ],
        ),
    ]
