# Generated by Django 5.2.17 on 2026-09-17 08:33

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_auditlog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopped_coming_after_days', models.PositiveIntegerField(default=apps.common.models._default_stopped_coming_after_days)),
            ],
        ),
    ]
