# Generated by Django 5.2.17 on 2026-09-09 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('patients', '0002_patient_client_created_at_patient_idempotency_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_kind', models.CharField(choices=[('monthly', 'Monthly service'), ('installment', 'Installment service')], db_index=True, max_length=16)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('informed_absence', 'Informed absence'), ('absent', 'Absent')], db_index=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('expected_return_on', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_attendance', to='branches.branch')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['branch', 'service_kind', 'date'], name='patients_pa_branch__60d09d_idx'), models.Index(fields=['patient', '-date'], name='patients_pa_patient_ee3a93_idx')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'service_kind', 'date'), name='uniq_patient_attendance_per_kind_day')],
            },
        ),
    ]
