# Generated by Django 5.2.17 on 2026-08-30 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=32)),
                ('therapist_count', models.PositiveIntegerField(default=0)),
                ('support_count', models.PositiveIntegerField(default=0)),
                ('opened_at', models.DateField()),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='branches_br_status_7730ae_idx')],
            },
        ),
    ]
